export let projectsData = [
  {
    name: 'MobileMen',
    company: 'Klein Buendel',
    description: 'Track ​physical ​activity. ​Encourage ​healthy ​behavior ​with education ​articles ​and ​notifications. ​Provided incentives ​to users by unlocking ​achievement ​and badges.',
    stack: 'Angular 5,​Ionic 3,​NgRx,​Node,​Express,MongoDB',
    galleryPath: 'mobilemen',
    galleryTotal: 27,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'dev.lopezhansel.com',
    company: 'Open Source',
    description: 'Personal website to display previous work done.',
    stack: 'React,Redux',
    galleryPath: 'lopezhansel',
    galleryTotal: 0,
    links: ['https://github.com/lopezhansel/lopezhansel.com/'],
    markdownUrl: undefined,
  },
  {
    name: 'WayToServe Español',
    company: 'Klein Buendel',
    description: 'IN-DEVELOPMENT. Way To Serve-Español is a state-approved training program to get alcohol server licence. Way To Serve trains employees for responsible beverage service. Way To Serve provides videos, graphics, quizes, and interactive activities that simulate real world experiences.',
    stack: 'Angular 5,RxJs',
    galleryPath: 'wts-es',
    galleryTotal: 4,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'Caminemos Juntas!',
    company: 'Creative Circle',
    description: 'Encourages ​Latinas ​to ​walk ​and ​engage ​in ​local community. ​App ​allows ​setting ​up ​meetups ​at ​parks. ​Supported ​English ​and Spanish ​languages.',
    stack: 'AngularJS,Ionic ​1,​Cordova,​Chart.js,​Node,​Express,MongoDB',
    galleryPath: 'caminemos',
    galleryTotal: 21,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'PMobile',
    company: 'Klein Buendel',
    description: 'Integrated ​with ​Fitbit ​API ​to ​promote ​physical ​activity ​through adaptive ​goals.',
    stack: 'AngularJS,Ionic ​1,​Cordova,​Chart.js,​Node,​Express,MongoDB',
    galleryPath: 'pmobile',
    galleryTotal: 11,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'CheckUp',
    company: 'Klein Buendel',
    description: '​Gather ​drinking ​habits ​data ​and ​provide ​strategic ​actions ​that encourage ​safe ​and ​healthy ​behavior ​while ​drinking.',
    stack: 'Angular 5,Ionic 3,​NgRx,​Node,​Express,MongoDB',
    galleryPath: 'checkup',
    galleryTotal: 22,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'WayToServe Admin',
    company: 'Klein Buendel',
    description: '',
    stack: 'React,​Node,​Express,MongoDB',
    galleryPath: 'wts-admin',
    galleryTotal: 0,
    links: [],
    markdownUrl: undefined,
  },
  {
    name: 'Velociti',
    company: 'RefactorU',
    description: 'A bike delivery app where you can request anything',
    stack: 'AngularJS,​Node,​Express,Socket.IO,MongoDB',
    galleryPath: 'velociti',
    galleryTotal: 0,
    links: ['https://github.com/lopezhansel/Velociti.co'],
    markdownUrl: undefined,
    // markdownUrl: 'https://raw.githubusercontent.com/lopezhansel/Velociti.co/master/readme.md',
  },
  {
    name: 'OctoDex',
    company: 'Open Source',
    description: 'E asily create and share a virtual business card using your Github information',
    stack: 'AngularJS,Node,​Express,MongoDB',
    galleryPath: 'octodex',
    galleryTotal: 12,
    links: ['https://github.com/lopezhansel/OctoDex'],
    markdownUrl: undefined,
  }
];