export let projects = [
  {
    name: 'Caminemos Juntas!',
    company: 'Creative Circle',
    description: 'Encourages ​Latinas ​to ​walk ​and ​engage ​in ​local community. ​App ​allows ​setting ​up ​meetups ​at ​parks. ​Supported ​English ​and Spanish ​languages.',
    stack: 'AngularJS,Ionic ​1,​Cordova,​Chart.js,​Node,​Express,MongoDB',
    galleryPath: 'caminemos',
    galleryTotal: 21,
  },
  {
    name: 'PMobile',
    company: 'Klein Buendel',
    description: 'Integrated ​with ​Fitbit ​API ​to ​promote ​physical ​activity ​through adaptive ​goals.',
    stack: 'AngularJS,Ionic ​1,​Cordova,​Chart.js,​Node,​Express,MongoDB',
    galleryPath: 'pmobile',
    galleryTotal: 11,
  },
  {
    name: 'MobileMen',
    company: 'Klein Buendel',
    description: 'Track ​physical ​activity. ​Encourage ​healthy ​behavior ​with education ​articles ​and ​notifications. ​Provided incentives ​to users by unlocking ​achievement ​and badges.',
    stack: 'Angular 5,​Ionic 3,​NgRx,​Node,​Express,MongoDB',
    galleryPath: 'mobilemen',
    galleryTotal: 27,
  },
  {
    name: 'CheckUp',
    company: 'Klein Buendel',
    description: '​Gather ​drinking ​habits ​data ​and ​provide ​strategic ​actions ​that encourage ​safe ​and ​healthy ​behavior ​while ​drinking.',
    stack: 'Angular 5,Ionic 3,​NgRx,​Node,​Express,MongoDB',
    galleryPath: 'checkup',
    galleryTotal: 22,
  },
  {
    name: 'WayToServe Admin',
    company: 'Klein Buendel',
    description: '',
    stack: 'React,​Node,​Express,MongoDB',
    galleryPath: '',
    galleryTotal: 0,
  },
  {
    name: 'WayToServe Español',
    company: 'Klein Buendel',
    description: '',
    stack: 'Angular 5',
    galleryPath: '',
    galleryTotal: 0,
  },
  {
    name: 'Velociti',
    company: 'RefactorU',
    description: '',
    stack: 'AngularJS,​Node,​Express,Socket.IO,MongoDB',
    galleryPath: '',
    galleryTotal: 0,
  },
  {
    name: 'OctoDex',
    company: 'Open Source',
    description: '',
    stack: 'AngularJS,Node,​Express,MongoDB',
    galleryPath: '',
    galleryTotal: 0,
  }
]